import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { User } from '@/types/user';
import type { SemesterWithCourses } from '@/types/semester';

interface Analytics {
  forecast?: {
    riskScore: number;
    trendLabel: string;
    projected: number[];
  };
  lastInsight?: {
    data: any;
  };
}

export function buildTranscript(userData: User, semesters: SemesterWithCourses[], analytics: Analytics | null): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // -- HEADER --
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('ENUGU STATE UNIVERSITY OF SCIENCE AND TECHNOLOGY', pageWidth / 2, 20, { align: 'center' });
  doc.setFontSize(12);
  doc.text('AGBANI, ENUGU STATE', pageWidth / 2, 26, { align: 'center' });
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('STUDENT UNOFFICIAL TRANSCRIPT', pageWidth / 2, 32, { align: 'center' });
  doc.text('Generated by AcadeGrade', pageWidth / 2, 37, { align: 'center' });

  // -- STUDENT DETAILS BOX --
  doc.setDrawColor(0);
  doc.setFillColor(245, 245, 245);
  doc.rect(14, 45, pageWidth - 28, 30, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  
  // Left Column
  doc.text(`Name:`, 18, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(userData.fullName, 45, 53);
  
  doc.setFont('helvetica', 'bold');
  doc.text(`Matric No:`, 18, 61);
  doc.setFont('helvetica', 'normal');
  doc.text(userData.matric || 'N/A', 45, 61);
  
  doc.setFont('helvetica', 'bold');
  doc.text(`Level:`, 18, 69);
  doc.setFont('helvetica', 'normal');
  doc.text(`${userData.currentLevel || 'N/A'}L`, 45, 69);

  // Right Column
  doc.setFont('helvetica', 'bold');
  doc.text(`Department:`, pageWidth / 2 + 10, 53);
  doc.setFont('helvetica', 'normal');
  doc.text(userData.department || 'N/A', pageWidth / 2 + 40, 53);
  
  doc.setFont('helvetica', 'bold');
  doc.text(`Programme:`, pageWidth / 2 + 10, 61);
  doc.setFont('helvetica', 'normal');
  doc.text(userData.programme || 'N/A', pageWidth / 2 + 40, 61);

  // Compute CGPA / Credits
  let totalPoints = 0;
  let totalCredits = 0;
  semesters.filter(s => s.isComplete).forEach(s => {
    totalCredits += s.creditLoaded || 0;
    totalPoints += (s.gpa || 0) * (s.creditLoaded || 0);
  });
  const cgpa = totalCredits > 0 ? (totalPoints / totalCredits).toFixed(2) : '0.00';
  
  // Predict Degree Class
  const cgpaNum = parseFloat(cgpa);
  let degreeClass = '';
  if (cgpaNum >= 4.5) degreeClass = 'First Class Honours';
  else if (cgpaNum >= 3.5) degreeClass = 'Second Class Honours (Upper Division)';
  else if (cgpaNum >= 2.4) degreeClass = 'Second Class Honours (Lower Division)';
  else if (cgpaNum >= 1.5) degreeClass = 'Third Class Honours';
  else degreeClass = 'Fail';

  // -- SEMESTER DATA --
  let currentY = 85;

  semesters.sort((a, b) => {
    if (a.level !== b.level) return a.level - b.level;
    return a.semester - b.semester;
  });

  semesters.forEach((sem) => {
    if (!sem.isComplete) return;

    // We build rows for autotable
    const body: Array<Array<string | object>> = sem.courses.map(course => [
      course.code,
      course.title.substring(0, 40),
      course.units.toString(),
      course.caScore?.toString() || '-',
      course.examScore?.toString() || '-',
      course.totalScore?.toString() || '-',
      course.grade || '-',
      course.gradePoint?.toString() || '-',
      ((course.units || 0) * (course.gradePoint || 0)).toString()
    ]);

    // Subtotal row
    body.push([
      { content: 'SEMESTER SUMMARY', colSpan: 2, styles: { fontStyle: 'bold', halign: 'right' } },
      { content: sem.creditLoaded.toString(), styles: { fontStyle: 'bold' } },
      { content: '', colSpan: 5 },
      { content: (sem.pi || 0).toString(), styles: { fontStyle: 'bold' } }
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [[
        { content: sem.label, colSpan: 9, styles: { halign: 'left', fillColor: [230, 230, 230], textColor: 0, fontStyle: 'bold' } }
      ], [
        'Code', 'Title', 'Units', 'CA', 'Exam', 'Total', 'Grade', 'GP', 'PI'
      ]],
      body: body,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      styles: { fontSize: 8, cellPadding: 2 },
      columnStyles: {
        0: { cellWidth: 20 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 12, halign: 'center' },
        3: { cellWidth: 12, halign: 'center' },
        4: { cellWidth: 12, halign: 'center' },
        5: { cellWidth: 12, halign: 'center' },
        6: { cellWidth: 12, halign: 'center' },
        7: { cellWidth: 12, halign: 'center' },
        8: { cellWidth: 12, halign: 'center' },
      },
      margin: { left: 14, right: 14 },
    });

    currentY = (doc as any).lastAutoTable.finalY + 10;
  });

  // -- CUMULATIVE SECTION --
  // Check page break
  if (currentY > pageHeight - 50) {
    doc.addPage();
    currentY = 20;
  }

  doc.setDrawColor(0);
  doc.rect(14, currentY, pageWidth - 28, 25);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('CUMULATIVE SUMMARY', 18, currentY + 7);
  
  doc.setFontSize(10);
  doc.text(`Cumulative CGPA: ${cgpa} / 5.00`, 18, currentY + 15);
  doc.text(`Total Credits Earned: ${totalCredits}`, 18, currentY + 21);
  
  doc.text(`Projected Degree Class:`, pageWidth / 2, currentY + 15);
  doc.setFont('helvetica', 'normal');
  doc.text(degreeClass, pageWidth / 2, currentY + 21);

  // -- FOOTER & PAGE NUMBERS --
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      'Generated by AcadeGrade · Not an official university document · Joshuazaza',
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, pageHeight - 10);
  }

  return doc;
}
