// List of Nigerian Universities (Alphabetized)
export const NIGERIAN_UNIVERSITIES = [
  "Abia State University, Uturu",
  "Abubakar Tafawa Balewa University, Bauchi",
  "Achievers University, Owo",
  "Adamawa State University, Mubi",
  "Adekunle Ajasin University, Akungba-Akoko",
  "Adeleke University, Ede",
  "Admiralty University of Nigeria, Ibusa",
  "Afe Babalola University, Ado-Ekiti",
  "African University of Science and Technology, Abuja",
  "Ahmadu Bello University, Zaria",
  "Ajayi Crowther University, Ibadan",
  "Akwa Ibom State University, Ikot Akpaden",
  "Alex Ekwueme Federal University, Ndufu-Alike",
  "Al-Hikmah University, Ilorin",
  "Ambrose Alli University, Ekpoma",
  "American University of Nigeria, Yola",
  "Augustine University, Ilara",
  "Babcock University, Ilishan-Remo",
  "Bauchi State University, Gadau",
  "Bayero University, Kano",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City",
  "Benue State University, Makurdi",
  "Bingham University, Karu",
  "Borno State University, Maiduguri",
  "Bowen University, Iwo",
  "Caleb University, Imota",
  "Chukwuemeka Odumegwu Ojukwu University, Uli",
  "Covenant University, Ota",
  "Delta State University, Abraka",
  "Ebonyi State University, Abakaliki",
  "Ekiti State University, Ado-Ekiti",
  "Enugu State University of Science and Technology, Enugu",
  "Federal University of Agriculture, Abeokuta",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University, Lafia",
  "Federal University, Lokoja",
  "Federal University, Otuoke",
  "Federal University, Oye-Ekiti",
  "Federal University, Wukari",
  "Gombe State University, Gombe",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Igbinedion University, Okada",
  "Ignatius Ajuru University of Education, Port Harcourt",
  "Imo State University, Owerri",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Kaduna State University, Kaduna",
  "Kwara State University, Ilorin",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Lagos State University, Ojo",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Michael Okpara University of Agriculture, Umudike",
  "Nasarawa State University, Keffi",
  "Niger Delta University, Wilberforce Island",
  "Olabisi Onabanjo University, Ago Iwoye",
  "University of Abuja, Abuja",
  "University of Benin, Benin City",
  "University of Calabar, Calabar",
  "University of Ibadan, Ibadan",
  "University of Ilorin, Ilorin",
  "University of Lagos, Lagos",
  "University of Nigeria, Nsukka",
  "University of Port Harcourt, Port Harcourt",
  "University of Uyo, Uyo"
];

// List of Academic Departments (Alphabetized)
export const ACADEMIC_DEPARTMENTS = [
  "Agric. Engineering",
  "Agric. Sc. Education",
  "Agricultural Economics & Extension",
  "Agronomy & Ecological Mgt.",
  "Animal Science & Fish Mgt.",
  "Architecture",
  "Banking and Finance",
  "Biology",
  "Biomedical Engineering",
  "Building Technology",
  "Building/ Woodwork Education",
  "Business and Entrepreneurship Education",
  "Chemical Engineering",
  "Chemistry Education",
  "Computer Science",
  "Computer Science Education",
  "Continuing Education and Development Studies",
  "Cooperative Economics and Management",
  "Economics",
  "Education Management",
  "Educational Administration and Supervision",
  "Educational Foundation",
  "Electrical/Elect. Technology Education",
  "English and Literary Studies",
  "Environmental Management",
  "Estate management",
  "Food Science and Technology",
  "Geography/Metrology",
  "Geology & Mining",
  "Guidance and Counselling",
  "History and International Studies",
  "Human Kinetics and Health Education",
  "Human Nutrition and Dietetics",
  "Industrial Chemistry",
  "Industrial Physics",
  "Information Technology",
  "Insurance and Risk Management",
  "Integrated Science Education",
  "Library and Information Science",
  "Marketing",
  "Mathematics",
  "Mathematics Education",
  "Mechanical Technology Education",
  "Mechatronics Engineering",
  "Metallurgical & Materials Engineering",
  "Physics Education",
  "Physics, Chemistry, Biology Education",
  "Psychology",
  "Quantity Surveying",
  "Sociology and Anthropology",
  "Software Engineering",
  "Statistics",
  "Surveying and Geoinformatics/Land Surveying",
  "Technology & Vocational Education",
  "Urban & Regional Planning"
];

// List of Academic Programmes
export const ACADEMIC_PROGRAMMES = [
  "Bachelor of Science (B.Sc.)",
  "Bachelor of Arts (B.A.)",
  "Bachelor of Engineering (B.Eng.)",
  "Bachelor of Laws (LL.B)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Pharmacy (B.Pharm)",
  "Bachelor of Technology (B.Tech)",
  "Bachelor of Education (B.Ed.)",
  "Bachelor of Agriculture (B.Agric)",
  "Bachelor of Medical Laboratory Science (BMLS)",
  "Postgraduate Diploma (PGD)",
  "Master of Science (M.Sc.)",
  "Master of Arts (M.A.)",
  "Master of Business Administration (MBA)",
  "Master of Engineering (M.Eng.)",
  "Doctor of Philosophy (PhD)",
  "Certificate/Diploma"
];
